version: "2.1"

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - cache

networks:
  cache:
    driver: bridge
  messaging:
    driver: bridge